version: 2.1

############################################################
# Shared Jobs and Configuration
############################################################

executors:
  node-executor:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/app

commands:
  attach-workspace-step:
    steps:
      - attach_workspace:
          at: ~/
  persist-workspace-step:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - app

############################################################
# Workflow
############################################################

workflows:
  version: 2.1
  pipeline:
    jobs:
      - install
      - lint:
          requires:
            - install
      - unit-test:
          requires:
            - install
      - e2e-test:
          requires:
            - install
      - sonar-scanner:
          requires:
            - unit-test
      - build-app:
          requires:
            - install
          filters:
            branches:
              only: main
      - deploy-prod:
          context: prod-jneal-s3
          requires:
            - lint
            - unit-test
            - e2e-test
            - sonar-scanner
            - build-app
      - prod-e2e-test:
          requires:
            - deploy-prod

############################################################
# Jobs
############################################################

jobs:

  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Reset Main Branch
          command: |
            if ["$CIRCLE_BRANCH" != "main"]; then
              git branch -f main origin/main
            fi
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package-lock.json" }}
            - node-dependencies-
      - run:
          environment:
            NG_CLI_ANALYTICS: ci
          name: Restore packages
          command: npm install
      - run:
          name: Disable Analytics
          command: npx ng analytics off
      - run:
          name: Precompile Angular libraries
          command: npx ngcc
      - save_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist-workspace-step

  lint:
    executor: node-executor
    steps:
      - attach-workspace-step
      - run:
          name: Lint code
          command: npm run lint

  unit-test:
    executor: node-executor
    steps:
      - attach-workspace-step
      - run:
          name: Run unit tests
          command: npm run test:cov
      - store_test_results:
          path: ./test-results
      - persist_to_workspace:
          root: ~/
          paths:
            - app/coverage

  e2e-test:
    executor: node-executor
    steps:
      - attach-workspace-step
      - run:
          name: Run e2e tests
          command: npm run e2e:ci
      - store_test_results:
          path: ./test-results

  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli
    working_directory: ~/app
    steps:
      - attach-workspace-step
      - restore_cache:
          key: sonar-plugins
      - run:
          name: Replace coverage paths
          command: sed -i "s+/home/circleci+/tmp+" coverage/jneal/lcov.info
      - run:
          name: Run sonar scanner
          command: |
            sonar-scanner \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.organization=jtneal \
              -Dsonar.projectKey=jtneal_jneal \
              -Dsonar.projectName=jneal \
              -Dsonar.projectVersion=$CIRCLE_SHA1 \
              -Dsonar.branch.name=$CIRCLE_BRANCH
      - save_cache:
          paths:
            - ~/.sonar/cache
          key: sonar-plugins-{{ epoch }}

  build-app:
    executor: node-executor
    steps:
      - attach-workspace-step
      - run:
          name: Build
          command: npm run build -- --prod
      - persist_to_workspace:
          root: ~/
          paths:
            - app/dist

  deploy-prod:
    docker:
      - image: amazon/aws-cli
    working_directory: ~/app
    steps:
      - run:
          name: Install tar
          command: yum --assumeyes install tar gzip
      - attach-workspace-step
      - run:
          name: Deploy to prod
          command: aws s3 sync dist/jneal s3://jneal.com/ --delete --cache-control "no-cache"
      - run:
          name: Invalidate cache
          command: aws cloudfront create-invalidation --distribution-id EEBT46KKHGG --paths "/*"

  prod-e2e-test:
    executor: node-executor
    steps:
      - attach-workspace-step
      - run:
          name: Run e2e tests
          command: npm run e2e:ci:prod
      - store_test_results:
          path: ./test-results
